name: nuget

on:
  push:
    branches: [ nuget ]
  pull_request:
    branches: [ nuget ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Restore
      run: dotnet restore 
    - name: Build
      run: dotnet build --configuration Release --no-restore 
    - name: Pack
      run: dotnet pack ZxTape2Wav.Net/ZxTape2Wav.Net.csproj --configuration Release --no-restore --output ./nupkgs --version-suffix --version-suffix .${{ github.run_number }}
    - name: Push
      run: dotnet nuget push ./nupkgs/ZxTape2Wav.Net.*.nupkg --source ${{secrets.NUGET_SOURCE}} --api-key ${{secrets.NUGET_API_KEY}} 
