name: release
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore 
    - name: Build win-x64
      run: dotnet publish ZxTape2Wav.Net/ZxTape2Wav.Net.csproj -r win-x64 -c Release --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true --no-restore && 
           zip -r -j zxtape2wave-win-x64.zip ./ZxTape2Wave/bin/Release/*/win-x64/publish/*
    - name: Build linux-x64
      run: dotnet publish ZxTape2Wav.Net/ZxTape2Wav.Net.csproj -r linux-x64 -c Release --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true --no-restore && 
           zip -r -j zxtape2wave-linux-x64.zip ./ZxTape2Wave/bin/Release/*/linux-x64/publish/*
    - name: Build osx-x64
      run: dotnet publish ZxTape2Wav.Net/ZxTape2Wav.Net.csproj -r osx-x64 -c Release --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true --no-restore && 
           zip -r -j zxtape2wave-osx-x64.zip ./ZxTape2Wave/bin/Release/*/osx-x64/publish/*
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        VERSION: 1.0.${{ github.run_number }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: ${{ env.VERSION }}
        draft: false
        prerelease: false
    - name: Upload Release Asset win-x64 
      id: upload-release-asset-win-x64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: zxtape2wave-win-x64.zip
        asset_name: zxtape2wave-win-x64.zip
        asset_content_type: application/zip
    - name: Upload Release Asset linux-x64 
      id: upload-release-asset-linux-x64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: zxtape2wave-linux-x64.zip
        asset_name: zxtape2wave-linux-x64.zip
        asset_content_type: application/zip
    - name: Upload Release Asset osx-x64 
      id: upload-release-asset-osx-64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: zxtape2wave-osx-x64.zip
        asset_name: zxtape2wave-osx-x64.zip
        asset_content_type: application/zip
